### PR TITLE
Add og:image meta property with the vertical logo to every page

### PR DESCRIPTION
**Pull request by skateman**

### CODE REVIEW

**Comment by skateman** [comment]
@hayesr this might help us look cooler when sharing a MIQ link on og-compatible websites, such as facebook.

**Comment by hayesr** [comment]
Cool, is there a way to test this?

**Comment by skateman** [comment]
I was afrait that you'll ask it :rofl:

**Comment by hayesr** [comment]
I think I've found a way to test. I'll check soon.

**Comment by hayesr** [comment]
screen shot 2017-05-17 at 4 46 09 pm

Looks a little awkward to me, but I'm fine with it if everyone else is fine with it. 
@cybette @JPrause ?

**Comment by skateman** [comment]
Well, I can create a new SVG with some extra whitespace around. Even add some background ...

**Comment by cybette** [comment]
This [article](https://www.h3xed.com/web-and-internet/how-to-use-og-image-meta-tag-facebook-reddit) has some recommendations for dimensions. Might be nice to have the graduated blue background as well.

**Comment by epwinchell** [comment]
This should work fine.
miq-logo

**Comment by skateman** [comment]
Updated with @epwinchell's image, @hayesr can you test it again? Also I'm not sure if I have it at the right location.

**Comment by cybette** [comment]
Wait.. is this going to put a huge logo on every facebook post? In that case I'd rather we go with a smaller version (400x400) so a square thumbnail is attached to posts instead, like [this](https://www.facebook.com/manageiq/posts/1160594917382993). It will look a lot better in a series of posts.

**Comment by skateman** [comment]
@cybette facebook compresses this image based on where it is linked and serves it through its CDN. If there is a large-enough image, it'll look like @hayesr posted previously.

**Comment by cybette** [comment]
@skateman and I'll like FB to use the smaller image to generate the square thumbnail. There's a reason Red Hat's og:image is 200x200 and not 1200x1200.

**Comment by skateman** [comment]
@cybette ok, resized to 200x200.

**Comment by hayesr** [comment]
How it looks currently:

screen shot 2017-05-18 at 10 47 03 am

The Facebook tester is complaining about missing tags, specifically `og:url` can we add that too? I think we should add the [required tags described here](http://ogp.me/#metadata).

**Comment by hayesr** [comment]
Actually, if everyone else is fine with the look then we can merge this and add the other tags in another PR.

**Comment by cybette** [comment]
Hmm, the jpeg artefacts are unfortunate, probably because of the blue background. Even using the large image in jpg form will result in artefacts. I think it's better we use png:
manageiq-logo-blue

Result will look like this:
capture

Additionally, we should use the full URL in the meta tag, because [this](https://meta.stackexchange.com/questions/264186/meta-should-use-a-full-url-for-its-open-graph-image), i.e.:
`<meta property="og:image" content="http://manageiq.org/assets/images/logo/manageiq-logo-blue.png" />`

**Comment by cybette** [comment]
@epwinchell could you generate the png from your source file? mine is converted from @skateman's image which is downsized from your jpg... anyway, it already shows some detail loss. sorry for the trouble, but if we do this let's do it right :smiley:

**Comment by epwinchell** [comment]
Sorry, @cybette. I missed your comment. Here's 200x200:

miq200

**Comment by skateman** [comment]
updated, thanks @epwinchell

**Pull request merged**
