### PR TITLE
Announcement for Hammer GA

### PR DESCRIPTION
**Pull request by cybette**
still WIP. initial commit.

### CODE REVIEW

**Comment by JPrause** [comment]
So far, so good. :+1:

**Comment by JPrause** [comment]
Thanks @simaishi 
So now the question is, who will merge? @cybette

**Comment by cybette** [comment]
Thanks @JPrause @simaishi! Let me make one more commit (minor formatting + image sizes) and maybe @epwinchell can merge.

**Comment by cybette** [comment]
@simaishi the docs will need some changes to the site menu and rebuilding the docs, we can do it in a separate PR like we did last release.

@JPrause 50 sprints? :grin: maybe you mean 50 weeks, but yeah, this is a big release and it was tough picking what to write about.

@epwinchell thank you!! :clinking_glasses:

**Comment by JPrause** [comment]
Ha! Yup, 50 weeks is what I meant.

**Pull request merged**
