### PR TITLE
Add required files for enabling the gaprindashvili docs generation

### PR DESCRIPTION
**Pull request by skateman**
@epwinchell I was able to generate it properly after @hayesr helped me in #625, please check it out.

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot assign epwinchell

**Comment by epwinchell** [comment]
@JPrause Tested. Looks fine.

**Comment by epwinchell** [comment]
@miq-bot assign @cybette

**Comment by skateman** [comment]
That's just an example file, so I don't think so.

**Comment by hayesr** [comment]
The example file does not need it, but the Dockerfile might (or it should be specified when the server launches the container —I can't remember exactly which we did 😄 )

**Comment by cybette** [comment]
Thanks @hayesr! I'll check the docker setup, but I still think the example file should contain all the updates we make so that in future if someone else copy the example file towards a new Docker setup they won't have to backtrack and figure out what is missing. @skateman please make that change and I can merge this.

**Comment by skateman** [comment]
@cybette done!

**Pull request merged**
