### PR TITLE
New download page

### PR DESCRIPTION
**Pull request by Fryguy**
@chessbyte @geertj @matthewd I wanted to see what it would look like (and how hard it would be) to create a simpler download page.  I can't seem to push to a webserver because all of the generated URLs are absolute, so a screencast will have to do.  This PR does not have the build_url or build_filenames working yet, but it does give a feel for how the page shows and hides stuff

What do you think?  The styling is terrible and I can't figure out how to do anything nice, so I'm starting to get into  very unfamiliar territory.

### CODE REVIEW

**Comment by chessbyte** [comment]
This is certainly an improvement over what we have now.  I (almost) always prefer many small steps over a giant leap forward.  So, I am :+1:

**Comment by geertj** [comment]
Looks great +1.

One thing that you could consider.. Right now you have to select your platform. I think it may be better to select the download format instead. That make it clearer to technical people what you are actually downloading. It allows you to decide which one to download if your platform is not listed (e.g. many platforms are compatible with QCOW2 or VMDK, e.g. VirtualBox).

So this could be:
- Choose Download Format ..
- OVA (VMware)
- OVA (oVirt, RHEV)
- QCOW2 (OpenStack, KVM, QEmu, ...)

**Comment by Fryguy** [comment]
@geertj That's very interesting.  The only problem is that the directions for the platforms are different, and I am using the dropdown to drive showing the right instructions.

**Comment by geertj** [comment]
@Fryguy - ah yes, you are correct. In that case let's make this change first as-is, so that we can keep the instructions as they are now.

**Comment by Fryguy** [comment]
OK, I'm just going to fix the warning, because I hate it, and then I'll un-WIP

**Comment by Fryguy** [comment]
Ph and of course I need to get the build_url and build_filename actually working..duh :)

**Comment by Fryguy** [comment]
OK, worked with @epwinchell and fixed the styling that was annoying me.  Screenshot below.  Now to get the URLs working.

download and install manageiq manageiq 2016-02-18 15-13-33

**Comment by Fryguy** [comment]
OK, everything is working...this is ready for merge.

**Comment by geertj** [comment]
:clap: :tada:

**Comment by chrisarcand** [comment]
Looks nice! :+1:

**Comment by geertj** [comment]
@Fryguy it appears that this change broke the following download links:

* RHEV (stable and nightly)
* VMware (stable and nightly)

**Pull request merged**
