### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by NickLaMuro**
Adds two 2 themes to `manageiq.org`:

- Light (default/current)
- Dark

Currently just uses browser/OS preference to select a theme.

TODO
----

- [x] Fix table hovering
- [x] Fix `pre`/`code` blocks in API docs
- [x] Fix bg/text colors for `/logos`
- [x] Fix `.btn-default`
- [x] Fix search results
- [x] Fix community Gitter buttons

### In followup...

- Add a theme switcher that uses local storage to save settings
- Add fix landing page icons

Screenshots
-----------

### Light

Screen Shot 2021-09-02 at 8 50 15 PM
Screen Shot 2021-09-02 at 8 50 26 PM
Screen Shot 2021-09-02 at 8 58 42 PM
Screen Shot 2021-09-02 at 8 51 15 PM

### Dark

Screen Shot 2021-09-02 at 8 49 14 PM
Screen Shot 2021-09-02 at 8 50 33 PM
Screen Shot 2021-09-02 at 8 51 06 PM
Screen Shot 2021-09-02 at 8 58 48 PM

### CODE REVIEW

**Comment by Fryguy** [comment]
This is AWESOME.  I'm ready to merge now :)

**Comment by Fryguy** [comment]
Ran it locally - I see a few super-minor things we can do a follow-up on

- Company logos looks strange on dark.  The backgrounds cycle light/dark and coincidentally the light aligns with the logos.  I wonder if we can use that and maybe make the light sections a little lighter?
- Logo page (manageiq.org/logo) needs the backgrounds reversed.  It is meant to show light logo on dark and dark logo on light, but it's showing dark on dark and light on gray
- Community (manageiq.org/community) page gitter buttons need styling.  Aside, I'd be fine with dropping that feature altogether as I doubt anyone uses it.
- Tables have the wrong color when you hover the dark rows.  This affects Downloads (manageiq.org/downloads), Sprints (manageiq.org/sprints), and Sprint details (click any sprint)
- Search Results is still white
- Some `code` stuff in the API is still messed up - See http://manageiq.org/docs/reference/latest/api/reference/collections.html for example

**Comment by NickLaMuro** [comment]
> Company logos looks strange on dark. The backgrounds cycle light/dark and coincidentally the light aligns with the logos. I wonder if we can use that and maybe make the light sections a little lighter?

@Fryguy Most of these make complete sense and I have realized where I forgot things, but this one I am a bit confused on.  Can you share a screenshot or a page where you see this?  I can do this one in a followup if needed.

**Comment by NickLaMuro** [comment]
Fixed a lot of things here, but definitely need to rebase.  Will try to do that in a bit... maybe tomorrow...

**Comment by Fryguy** [comment]
> > Company logos looks strange on dark. The backgrounds cycle light/dark and coincidentally the light aligns with the logos. I wonder if we can use that and maybe make the light sections a little lighter?
> 
> @Fryguy Most of these make complete sense and I have realized where I forgot things, but this one I am a bit confused on. Can you share a screenshot or a page where you see this? I can do this one in a followup if needed.

Yes this can be done in a followup, but here's the screenshots.  I realize my description wasn't clear, but what I observed is that coincidentally the company logos landed on horizontal stripes where there were "lighter" backgrounds, so I was wondering if we could leverage that somehow.

ManageIQ

**Comment by NickLaMuro** [comment]
@Fryguy Oh right!  Yeah, I definitely saw that as well.  Not sure the best way to handle it, but I will look into it.  Thinking `.svg` files with class tags that could modified based on the theme currently in use, but unsure if that is Kosher with the brands.

**Comment by NickLaMuro** [comment]
So, at least for the "could be made light" section you have above, I have been looking at a bunch of different options.  The main idea is part of the `[_partners.scss] Theme based filters` commit, but I have a follow up as well, along with one tweak I haven't commited.  The results of the ones that I think make the most sense are as follows:

### `invert(100%) grayscale(100%)`

Screen Shot 2021-09-13 at 2 19 12 PM

### `invert(100%) contrast(.5) saturate(2) brightness(2) grayscale(100%)`

Screen Shot 2021-09-13 at 2 19 22 PM


### `invert(100%) contrast(.5) saturate(2) brightness(1.5) grayscale(100%)`

Screen Shot 2021-09-13 at 2 19 29 PM


* * *

Even a slight tweak to `brightness` (2 to 1.5) can have a drastic difference, and it mostly is a matter of taste and trying to balance things with the rest of the logos.  I specifically set out to try and make the Red Hat logo not stick out so much (and try to make the "hat band" be dark even after inverting, but I haven't found a way to do that yet, might try something in a bit).

I will try a few more things, but also want to work on some of the other images on that page.

**Comment by Fryguy** [comment]
They all look great!  I think I like the 3rd one the best - you can really see the difference with the Google logo. thought the xclarity logo loses that "dark band", it still looks great.  I'm honestly good with any of these 3.

**Comment by NickLaMuro** [comment]
So... I figured out how to make the "Red Hat" look reasonable... but it is a bit of a hack.

Screen Shot 2021-09-13 at 3 43 57 PM

I will save it for a followup, because unclear if he extra "dark mode specific rule" is worth the effort for splitting hairs like this.

**Comment by NickLaMuro** [comment]
@Fryguy Okay, I think I have this in a good state now.  Thanks for your patience!

**Pull request merged**
