### PR TITLE
Add LWIMIQ 2016-10-10

### PR DESCRIPTION
**Pull request by imtayadeway**
@hayesr LMK if I need to do anything special for this to be deployed. Thanks!

### CODE REVIEW

**Comment by JPrause** [comment]
@syncrou @juliancheal @ZitaNemeckova @himdel can you please review Tim's blog entry. We'd like to get all suggestions and edits completed for today's merge.

**Comment by JPrause** [comment]
LGTM,...thanks @imtayadeway.

**Comment by syncrou** [comment]
@imtayadeway - Looks great! (only issue I see is the total counts) - I really like the emojis!

**Comment by juliancheal** [comment]
Bit late to the party, but 👍 LGTM.

**Pull request merged**
