### PR TITLE
Add January blog post

### PR DESCRIPTION
**Pull request by d-m-u**
✨

### CODE REVIEW

**Comment by JPrause** [comment]
My favorite of the pole whost:  "warsing this pork"

TMLG!!!

**Comment by JPrause** [comment]
@imtayadeway @syncrou @jntullo and especially my proper-English-speaking friend @juliancheal can you review.

**Comment by jntullo** [comment]
😆  TMLG! ✨

**Comment by syncrou** [comment]
It's tanfabulous.  Mo tany preat goints to comment on. 👎

**Comment by cybette** [comment]
🤯

**Pull request merged**
