### PR TITLE
Adds 11-13 post

### PR DESCRIPTION
**Pull request by d-m-u**
✨

### CODE REVIEW

**Comment by JPrause** [comment]
I couldn't find a dictionary for most of the words, so I'm just going with LGTM.

**Comment by syncrou** [comment]
Paging through my tabs today I fell upon what some would say is a gem.  A ruby of sorts, but not red or crimson, a figment, a process, a parser.

The words herein describe the magic produced by moving hands, some would say fingers, over letters on a plastic or mechanical interface. 

The letters form words not readable by only one language, but readable mostly via many different languages.  The fingers that type these prose by passing them to this gem transform such language into art.  In our case such art is our product.  The words herein this (heretofore blog post) describe the many letters 'typed' by said phalanges and the result breathed into them by said magical compiler.  I just give a special fist with a single finger pointing upward to provide what some would say is the ultimate approval of said prose.  

In laymen's terms.  LGTM 👍

**Comment by JPrause** [comment]
@jntullo @imtayadeway if you have a few minutes, can you also review.

**Comment by JPrause** [comment]
@cybette can you review and merge if all looks good.

**Pull request merged**
