### PR TITLE
Blog post about Hawkular alerts

### PR DESCRIPTION
**Pull request by israel-hdez**

### CODE REVIEW

**Comment by israel-hdez** [comment]
@miq-bot add_label blog post
cc @abonas

**Comment by JPrause** [comment]
LGTM! Awesome walk-through.

**Comment by JPrause** [comment]
@cybette if all look good to you, can you merge this article.

**Comment by cybette** [comment]
Hi @israel-hdez, Thanks for the blog post!

I see that this was published last week on the [Hawkular blog](http://www.hawkular.org/blog/2017/10/alerts-in-manageiq.html). In general we try not to have duplicate posts to avoid problems with search results/page rank. In this case I think it's ok since the posting dates are far enough apart, and you have additional intro in the ManageIQ post. In future may I suggest [this format](http://community.redhat.com/blog/2017/05/manageiq-fine-ga-announcement/) when cross-posting, i.e. a section of the article with link back to the original post.

Can you please add this one at the end of the post, and then I can merge it? Thanks!

_This post was originally published on the [Hawkular Blog](http://www.hawkular.org/blog/2017/10/alerts-in-manageiq.html) on 11 October 2017._

**Comment by israel-hdez** [comment]
@cybette ok, I'll remember your advice next time.
I added the note at the end.

**Comment by cybette** [comment]
Thanks @israel-hdez! Merging after checks are completed.

**Pull request merged**
