### PR TITLE
Add Hawkular Provider to the community view

### PR DESCRIPTION
**Pull request by aljesusg**
I add the repo of Hawkular to the community site.

screenshot from 2017-11-02 13-15-16

### CODE REVIEW

**Comment by JPrause** [comment]
LGTM 👍 
@cybette seems to me, there are a lot more repos that could added. But we can talk offline and handle in another PR.

**Comment by JPrause** [comment]
@Fryguy do you have any opinion on what repos are listed here? ie, do we list 80+ repos, if not which ones.

**Comment by aljesusg** [comment]
I can add the others repos but there are many repos now under manageiq/

**Comment by JPrause** [comment]
No worries @aljesusg,..I think we'll need to discuss offline first and then work in another PR. I don't think we need to hold this PR up.

**Pull request merged**
