### PR TITLE
Set blogpost content paragraphs to align: justify

### PR DESCRIPTION
**Pull request by skateman**
**Before:**
screenshot from 2017-01-31 11-36-52

**After:**
screenshot from 2017-01-31 11-36-32

### CODE REVIEW

**Comment by skateman** [comment]
@hayesr what do you think?

**Comment by hayesr** [comment]
@skateman Sorry for the delay, I have been thinking about it though.

My concern with this is the tendency of justified text to form [rivers](https://en.wikipedia.org/wiki/River_(typography)), left-justified text doesn't have this problem. With the site trying to be responsive it makes it even more difficult to avoid this happening.

I've been meaning to play with this PR to see how bad the river effect actually would be and just haven't got to it yet.

**Comment by JPrause** [comment]
@skateman and @cybette what are we going to do with this change.
I know Eric had reservations.

@skateman do you feel strongly about this? If not then close and we can revisit at a later time.
If yes,...then perhaps we merge and see what the net results looks like.

This has been open almost a year.

**Comment by skateman** [comment]
We have a new Eric working on the website, can we ask him? :wink:  @epwinchell

**Comment by cybette** [comment]
This may be more of a personal preference, I prefer left to justify. In addition, most websites and blogs use the default (left). Not that we have to conform, but unless there's a strong justification (reason) to use this justification (alignment), I'd rather we leave it as it is.

Also, this PR will only change the alignment for blog posts, and not the rest of the site. We'll break the visual consistency of the website.

**Comment by JPrause** [comment]
Thanks @cybette for your perspective. @epwinchell your thoughts?
I'm leaning towards Carol's reasoning.

I'd rather not have this PR linger for another 10 months.
Either way, we should merge, or let's close this today.

**Comment by JPrause** [comment]
@epwinchell thanks for testing.
@skateman can you close this PR. Perhaps at a later time, we can revisit if there's a better way to format.

**Pull request closed without merging**
