### PR TITLE
Compute url file sizes for downloads

### PR DESCRIPTION
**Pull request by chessbyte**
Fixes https://github.com/ManageIQ/manageiq.org/issues/694

Here is a snapshot of the resulting screen (partial view):

Screen Shot 2020-04-03 at 5 29 12 PM

### CODE REVIEW

**Comment by Fryguy** [comment]
cc @simaishi

**Comment by Fryguy** [comment]
cc @bdunne

**Comment by bdunne** [comment]
> cc @bdunne - will this be affected if we move to another hosting?

It should be fine, the options I'm looking at return the `content-length` header.

**Comment by Fryguy** [comment]
Not necessarily for this PR, but:

For docker, I think this helps: https://stackoverflow.com/a/55156181/2355944
For vagrant, we also have the image in releases.manageiq.org, even though we point to an external URL for the link.

**Comment by chessbyte** [comment]
@Fryguy incorporated your suggestion about vagrant.

Screen Shot 2020-04-04 at 8 31 12 AM

**Pull request merged**
