### PR TITLE
Add UI to Dev Guides Menu

### PR DESCRIPTION
**Pull request by epwinchell**
Issue: #423

Screen Shot 2019-03-15 at 11 03 59 AM

### CODE REVIEW

**Comment by cybette** [comment]
There are additional UI sections in addition to Patterns and Plugins. Should we add a link from the parent menu "User Interface" to http://manageiq.org/docs/guides/ui/ ?

**Comment by epwinchell** [comment]
`There are additional UI sections in addition to Patterns and Plugins. Should we add a link from the parent menu "User Interface" to http://manageiq.org/docs/guides/ui/ ?`

@cybette Nearly everything in  http://manageiq.org/docs/guides/ui/ is included in UI Patterns.  I'd suggest we address any discrepancies in the guides repo. I can open an issue there.

**Comment by epwinchell** [comment]
> There are additional UI sections in addition to Patterns and Plugins. Should we add a link from the parent menu "User Interface" to http://manageiq.org/docs/guides/ui/ ?

@cybette linking to /ui/ would just  spill out the folder contents. Nearly everything in  http://manageiq.org/docs/guides/ui/ is included in UI Patterns. I've added a couple additional items to the menu - I think it's all covered now. I will do some follow-up work in the guides repo.

**Comment by cybette** [comment]
Sounds good, thanks @epwinchell!

**Pull request merged**
