### PR TITLE
Renaming the last 2 last week in manageiq posts to make the urls different

### PR DESCRIPTION
**Pull request by himdel**
If the filenames differ only in the day of the month, both will get the same url and only the last one becomes available.

Without this, going to http://manageiq.org/blog/2016/08/ and clicking on the Aug 9 link opens the Aug 15 post..

### CODE REVIEW

**Comment by chrisarcand** [comment]
LGTM 👍  :shipit:

**Comment by himdel** [comment]
Updated to only rename David's .. and another commit to unify the extensions.

**Comment by chrisarcand** [comment]
👍  LGTM :shipit:

**Comment by JPrause** [comment]
Thanks all!! :+1:

**Pull request merged**
