### PR TITLE
Announcing Darga-3

### PR DESCRIPTION
**Pull request by JPrause**
Initial submission for review.
Review and edits to be completed by Aug 22
Merge on release date of darga3 which is slated for Aug 22

### CODE REVIEW

**Comment by geertj** [comment]
@JPrause can we add a small changelog with the fixes since darga-2?

**Comment by JPrause** [comment]
@geertj will do and thanks for the input. Will add to the PR shortly.

**Comment by Fryguy** [comment]
Does it matter that the filename does not match the title?  I know that the blog is very picky about things... cc @chrisarcand @himdel Do you know?

**Comment by Fryguy** [comment]
The announcement should really detail the CVE as well.

**Comment by Fryguy** [comment]
Also @JPrause I *think* you have to add yourself to the [authors.yml file](https://github.com/ManageIQ/manageiq.org/blob/master/data/authors.yml) or your blog post won't render

**Comment by chrisarcand** [comment]
> Does it matter that the filename does not match the title?

It shouldn't, for the website's concern. I have no idea what the connection is between the blog and talk.manageiq.org links though. 😕

**Pull request merged**
