### PR TITLE
Update homepage images

### PR DESCRIPTION
**Pull request by epwinchell**
This PR updates the homepage images with the ones created for the Community collateral.

Before:
screen shot 2017-07-07 at 1 23 25 pm

After:
screen shot 2017-07-07 at 1 21 26 pm 1

Before:
screen shot 2017-07-07 at 1 23 16 pm

After:
screen shot 2017-07-07 at 1 21 11 pm

### CODE REVIEW

**Comment by epwinchell** [comment]
@miq-bot assign @cybette

**Comment by JPrause** [comment]
@epwinchell nice! I especially like how you added the MIQ "Q" to the optimization icon.
LGTM! 👍

**Comment by cybette** [comment]
This is great! Thanks for updating this, @epwinchell :smile:

**Comment by hayesr** [comment]
Ooo pretty 😍

**Pull request merged**
