### PR TITLE
Fill humans.txt with real data

### PR DESCRIPTION
**Pull request by RoxasShadow**
Content generated by [humanity](https://github.com/RoxasShadow/humanity).

### CODE REVIEW

**Comment by JPrause** [comment]
Look like this PR can be closed as the humans.txt now has updated data.

**Comment by RoxasShadow** [comment]
Hm, it is not on [remote/master](https://github.com/ManageIQ/manageiq.org/blob/master/source/humans.txt) from what I can see

**Comment by JPrause** [comment]
Sorry,...I misspoke. We provide the data here: data/team.yml

**Comment by RoxasShadow** [comment]
Cool 👍

**Pull request closed without merging**
