### PR TITLE
Edits to Fine Beta downloads

### PR DESCRIPTION
**Pull request by cybette**
Updating Fine Beta download file sizes with most recent info from John; add Google Analytics to download links in Fine Beta blog post to track downloads; update Vagrant link from Euwe to Fine.

### CODE REVIEW

**Comment by cybette** [comment]
@JPrause @hayesr please have a check. I did a quick test to make sure links are fine (and Fine). I'd like to have the GA stuff in before doing Social push for the blog post. Thanks!

**Comment by JPrause** [comment]
LGTM

**Comment by cybette** [comment]
Thanks @jprause. @hayesr can you please merge?

**Comment by JPrause** [comment]
@hayesr can you merge asap. Carol needs to announce this release on social media once this is merged.

**Pull request merged**
