### PR TITLE
Add raw tags so the things show up right

### PR DESCRIPTION
**Pull request by d-m-u**
Screen Shot 2020-02-18 at 11 45 38 AM

Things and stuff in double curly braces are empty unless they have raw tags even inside a code block :( 

@cybette please review, thanks

### CODE REVIEW

**Comment by cybette** [comment]
Braces are tricky...

**Comment by d-m-u** [comment]
@pemcg I think this is all for the first three that were wrong

**Comment by cybette** [comment]
` ```console `

Can you try this at the start of a code block? based on https://github.com/ManageIQ/manageiq.org/pull/669

**Comment by d-m-u** [comment]
@cybette that still looks like it needs raw tags:
Screen Shot 2020-02-18 at 12 07 15 PM

see the empty "gateway" line

**Comment by cybette** [comment]
ok I guess console mainly makes things prettier. I'll merge this, thanks for checking!

**Pull request merged**
