### PR TITLE
Add embedded ansible post two

### PR DESCRIPTION
**Pull request by d-m-u**
Peter wrote 4 articles about embedded Ansible work in CFME 4.5 that were intended for posting on the CloudFormsNow site but aren't going to all get posted and so I was asked to put them here since it's a shame to waste the research and time that went into this effort. They're great, and we should post them, part two.

~~WIP cause I'm working on the formatting.~~

Part 1 is here: https://github.com/ManageIQ/manageiq.org/pull/796

### CODE REVIEW

**Comment by d-m-u** [comment]
@cybette and @pemcg could I please have your 👀 ?

**Comment by cybette** [comment]
:eyes: GTM!

When @pemcg gives the OK, I can merge the first 2 posts

**Comment by pemcg** [comment]
LGTM 👍

**Comment by d-m-u** [comment]
@cybette if you merge 1, could you hold off on two and three so I can set the links properly on those two to point to 1 please? And same with two and three when I get there?

**Comment by cybette** [comment]
Link to part 1: https://www.manageiq.org/blog/2020/02/Embedded-Ansible-Part-1-Built-In-Roles/

**Comment by d-m-u** [comment]
@cybette anything else this needs?

**Pull request merged**
