### PR TITLE
Updating terms for manageiq documentation.

### PR DESCRIPTION
**Pull request by JPrause**
Added additional terms to: http://manageiq.org/documentation/terms/

### CODE REVIEW

**Comment by sergio-ocon** [comment]
👏

**Comment by hayesr** [comment]
I'm not sure where we're going to incorporate this into the new site; will have to discuss.

**Comment by sergio-ocon** [comment]
There is the concepts guide in the getting started guide, we could move it to its own or incoporate these there.

**Comment by sergio-ocon** [comment]
I've updated the concept guide in the new website ( #366 ) with all these term:
- I've changed CloudForms ME to ManageIQ
- I've added some definitions that were missing (like RBAC or SSUI)

**Comment by JPrause** [comment]
@sergio-ocon so it seems I can close this PR. Does that seem reasonable to you,..or did I misunderstand.

**Comment by sergio-ocon** [comment]
Yes, you can close it.

All the content is now in the new webpage, I was already doing a terms page there in the getting started guide.

Do you think it should be more prominent?

**Comment by JPrause** [comment]
Sounds good,..closing PR.

**Pull request closed without merging**
