### PR TITLE
Move news to navigation

### LINKED ISSUE #173: add "blog" top level link
We should add a "Blog" link to the main page header. It should link to /blog.

### PR DESCRIPTION
**Pull request by matthewd**
Fixes #173

Before:
news-before

After:
news-after

### CODE REVIEW

**Comment by chessbyte** [comment]
@matthewd should we call it `news` or `blog`?  /cc @Fryguy @geertj @mfeifer

**Comment by geertj** [comment]
I think blog gives us a little more flexibility. This means we can also publish opinion or technical pieces that are technically now news, but nevertheless useful.

**Comment by chessbyte** [comment]
@geertj We will change the title when we have something `bloggy` there.  For now, it is all news.  Merging and we can change this later.

**Comment by geertj** [comment]
Sounds good @chessbyte

**Pull request merged**
